# Generated by Django 4.0.3 on 2024-03-03 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='names',
            new_name='name',
        ),
    ]
